---
namespace: rhpds
name: openshift_lightspeed_demo
version: 1.0.0
readme: README.md
authors:
- Prakhar Srivastava <psrivast@redhat.com>
description: OpenShift Lightspeed Demo Workloads Collection
license:
- Apache-2.0
license_file: ''
tags:
- openshift
- virtualization
- lightspeed
- demo
dependencies: {}
repository: https://github.com/rhpds/rhpds.openshift_lightspeed_demo
documentation: https://github.com/rhpds/rhpds.openshift_lightspeed_demo
homepage: https://github.com/rhpds/rhpds.openshift_lightspeed_demo
issues: https://github.com/rhpds/rhpds.openshift_lightspeed_demo/issues
build_ignore:
- .gitignore
- .DS_Store
