---
- name: Create Perses UIPlugin
  kubernetes.core.k8s:
    state: present
    template: perses_uiplugin.yaml.j2

- name: Create Perses Global Datasource
  kubernetes.core.k8s:
    state: present
    template: perses_global_datasource.yaml.j2
