---
- name: Create troubleshooting namespace
  kubernetes.core.k8s:
    state: present
    wait: true
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ ocp4_workload_lightspeed_demo_troubleshooting_namespace }}"
        labels:
          app.kubernetes.io/name: critical-service
          app.kubernetes.io/part-of: critical-system

- name: Wait for default ServiceAccount to exist
  kubernetes.core.k8s_info:
    api_version: v1
    kind: ServiceAccount
    name: default
    namespace: "{{ ocp4_workload_lightspeed_demo_troubleshooting_namespace }}"
  register: r_sa
  until: r_sa.resources | length > 0
  retries: 10
  delay: 3

- name: Deploy troubleshooting case resources
  kubernetes.core.k8s:
    template: deploy_troubleshooting_case.yaml.j2
    wait: false
